import KRTheory.TransMon.WreathDivision
import KRTheory.TransMon.Bar
import KRTheory.TransMon.LocalDivisor

/-!
# The decomposition theorem

[DKS] Theorem 3.1 [spec §3.8 as amended, blueprint `ch:decomposition`]:
a faithful transformation monoid generated by a submonoid `N` and a
non-unit `c` is covered, after barring, by the wreath of its barred
local divisor at `c` with the barred right factor on `X ⊕ N`. This is
the engine of milestone 8's induction.

The construction follows [DKS] §3's generator covers, with the tag
strengthening recorded in blueprint `rem:bar-gap`: our syntactic bar
forces cover selection by a front-shape tag rather than faithfulness.
-/

namespace KRTheory
namespace TransMon

/-- The right factor of [DKS] Thm 3.1 [blueprint `def:right-factor`]:
states `T.X ⊕ ↥N`, monoid `↥N`, restriction on the left summand and
right multiplication (the regular action) on the right. The regular
summand is what keeps this faithful, so milestone 8 can recurse into
it. -/
def rightFactor (T : TransMon) (N : Submonoid T.M) : TransMon where
  X := T.X ⊕ ↥N
  M := ↥N
  act y n := match y with
    | .inl x => .inl (T.act x ↑n)
    | .inr n' => .inr (n' * n)
  act_one y := by cases y <;> simp
  act_mul y n n' := by cases y <;> simp [mul_assoc]

/-- Original states move by restriction. -/
@[simp] theorem rightFactor_act_inl (T : TransMon) (N : Submonoid T.M)
    (x : T.X) (n : ↥N) :
    (rightFactor T N).act (.inl x) n = .inl (T.act x ↑n) := rfl

/-- Regular states move by right multiplication. -/
@[simp] theorem rightFactor_act_inr (T : TransMon) (N : Submonoid T.M)
    (n' n : ↥N) :
    (rightFactor T N).act (.inr n') n = .inr (n' * n) := rfl

/-- The right factor is faithful [blueprint `lem:right-factor-faithful`]:
evaluate at the regular point `1`. -/
theorem rightFactor_faithful (T : TransMon) (N : Submonoid T.M) :
    (rightFactor T N).Faithful := by
  intro n n' h
  have hM : (rightFactor T N).M = ↥N := rfl
  have h1 : (Sum.inr ((1 : ↥N) * cast hM n) : T.X ⊕ ↥N) = Sum.inr ((1 : ↥N) * cast hM n') :=
    h (.inr 1)
  have h2 : cast hM n = cast hM n' := by simpa [one_mul] using h1
  exact h2

/-- Faithful + a non-unit forces nonempty states [blueprint
`lem:nonempty-of-nonunit`]: with no states faithfulness collapses `M`. -/
theorem nonempty_of_not_isUnit {T : TransMon} (hT : T.Faithful)
    {c : T.M} (hc : ¬ IsUnit c) : Nonempty T.X := by
  by_contra h
  exact hc (by
    have hc1 : c = 1 := hT (fun x => absurd ⟨x⟩ h)
    exact hc1 ▸ isUnit_one)

/-- Bar generation [blueprint `lem:bar-generated`]: generators of `M`
plus the resets generate the bar monoid. -/
theorem barMonoid_closure {T : TransMon} {s : Set T.M}
    (hs : Submonoid.closure s = ⊤) :
    Submonoid.closure
      ((BarMonoid.of '' s) ∪ (Set.range (BarMonoid.reset (T := T)))) = ⊤ := by
  rw [eq_top_iff]
  rintro b -
  cases b with
  | of m =>
    refine Submonoid.closure_induction
      (motive := fun m _ => (BarMonoid.of m : BarMonoid T) ∈ Submonoid.closure
        ((BarMonoid.of '' s) ∪ Set.range (BarMonoid.reset (T := T))))
      (fun x hx => Submonoid.subset_closure (Or.inl ⟨x, hx, rfl⟩))
      (by rw [← BarMonoid.one_def]; exact one_mem _)
      (fun x y _ _ ihx ihy => by
        rw [← BarMonoid.of_mul_of]
        exact mul_mem ihx ihy)
      (hs ▸ Submonoid.mem_top m)
  | reset x =>
    exact Submonoid.subset_closure (Or.inr ⟨x, rfl⟩)

-- Sanity (spec §6). Right-factor chirality guard: over the
-- noncommutative regular (Equiv.Perm (Fin 3)) with N := ⊤, the regular
-- summand must multiply ON THE RIGHT: a transposed definition
-- (n * n') would give the other product; swap 0 1 and swap 1 2 differ.
example :
    (rightFactor (regular (Equiv.Perm (Fin 3))) ⊤).act
      (.inr ⟨Equiv.swap 0 1, trivial⟩) ⟨Equiv.swap 1 2, trivial⟩ =
    .inr ⟨Equiv.swap 0 1 * Equiv.swap 1 2, trivial⟩ := rfl
example : (Equiv.swap 0 1 * Equiv.swap 1 2 : Equiv.Perm (Fin 3)) ≠
    Equiv.swap 1 2 * Equiv.swap 0 1 := by decide
example : (rightFactor (regular (ZMod 4)) ⊤).Faithful :=
  rightFactor_faithful _ _
example : Nonempty (regular (ZMod 4)).X :=
  nonempty_of_not_isUnit (regular_faithful _) (c := (2 : ZMod 4))
    (by show ¬ IsUnit (2 : ZMod 4); decide)

end TransMon
end KRTheory
