import Mathlib.Tactic

/-!
# Finite monoid preliminaries

Counting and unit lemmas for finite monoids [spec §3.6 prelims,
blueprint ch. `ch:finitemonoid`]. Mathlib already supplies the
one-sided-inverse lemmas (`mul_eq_one_comm`,
`IsUnit.of_mul_eq_one_right`) and the subtype-count lemma
(`Finite.card_subtype_lt`); this file holds the idempotent-power
lemma (still an upstream candidate, spec §9) and milestone 8's
generating-set prelims.
-/

namespace KRTheory

variable {M : Type} [Monoid M] [Finite M]

/-- Every element of a finite monoid has an idempotent power `a ^ n`,
`n ≥ 1` [blueprint `lem:idem-pow`]. Pigeonhole gives `a ^ i = a ^ j`
with `i < j`; the period `p := j - i` then absorbs (`a ^ (k + p) =
a ^ k` for `k ≥ i`), and `n := p * (i + 1)` is a multiple of `p` at
least `i`. -/
theorem exists_pow_idempotent (a : M) :
    ∃ n : ℕ, 0 < n ∧ IsIdempotentElem (a ^ n) := by
  -- pigeonhole: two powers coincide
  obtain ⟨s, t, hne, hst⟩ :=
    Finite.exists_ne_map_eq_of_infinite (fun n : ℕ => a ^ n)
  obtain ⟨i, j, hlt, hij⟩ : ∃ i j : ℕ, i < j ∧ a ^ i = a ^ j := by
    rcases lt_or_gt_of_ne hne with h | h
    · exact ⟨s, t, h, hst⟩
    · exact ⟨t, s, h, hst.symm⟩
  set p := j - i with hp
  have hp1 : 0 < p := by omega
  -- one period absorbs past the ramp `i`
  have hstep : ∀ t : ℕ, a ^ (i + t + p) = a ^ (i + t) := by
    intro t
    have h1 : i + t + p = j + t := by omega
    rw [h1, pow_add, pow_add, ← hij]
  -- …hence any number of periods
  have habs : ∀ m t : ℕ, a ^ (i + t + m * p) = a ^ (i + t) := by
    intro m
    induction m with
    | zero => intro t; simp
    | succ m ihm =>
      intro t
      have h1 : i + t + (m + 1) * p = i + (t + m * p) + p := by
        rw [Nat.succ_mul]; omega
      rw [h1, hstep (t + m * p)]
      have h2 : i + (t + m * p) = i + t + m * p := by omega
      rw [h2, ihm t]
  -- the witness: a p-multiple past the ramp
  have hile : i + 1 ≤ p * (i + 1) := Nat.le_mul_of_pos_left _ hp1
  refine ⟨p * (i + 1), by positivity, ?_⟩
  set t₀ := p * (i + 1) - i with ht₀
  have hsplit : p * (i + 1) = i + t₀ := by omega
  have e1 : p * (i + 1) + p * (i + 1) = i + t₀ + (i + 1) * p := by
    rw [Nat.mul_comm (i + 1) p]; omega
  show a ^ (p * (i + 1)) * a ^ (p * (i + 1)) = a ^ (p * (i + 1))
  calc a ^ (p * (i + 1)) * a ^ (p * (i + 1))
      = a ^ (p * (i + 1) + p * (i + 1)) := (pow_add a _ _).symm
    _ = a ^ (i + t₀ + (i + 1) * p) := by rw [e1]
    _ = a ^ (i + t₀) := habs (i + 1) t₀
    _ = a ^ (p * (i + 1)) := by rw [← hsplit]

-- Sanity (spec §6): in `ZMod 4`, the element `2` squares to `0`, and
-- `0` is idempotent; `exists_pow_idempotent` must therefore be
-- satisfiable at `n = 2` — witness check, plus the generic call.
example : IsIdempotentElem ((2 : ZMod 4) ^ 2) := by
  -- `show` unfolds the semireducible `IsIdempotentElem` so `decide`
  -- finds its `Decidable` instance at the bare equation
  show (2 : ZMod 4) ^ 2 * (2 : ZMod 4) ^ 2 = (2 : ZMod 4) ^ 2
  decide
example : ∃ n : ℕ, 0 < n ∧ IsIdempotentElem ((2 : ZMod 4) ^ n) :=
  exists_pow_idempotent 2

omit [Finite M] in
/-- A monoid generated by units consists of units [blueprint
`lem:units-generated`]: closure induction — `1` is a unit and units
multiply. The §3.9 branch fact: if the non-group branch runs, some
generator is a non-unit. Needs no finiteness. -/
theorem isUnit_of_generators_units (A : Set M)
    (hA : Submonoid.closure A = ⊤) (h : ∀ a ∈ A, IsUnit a) (m : M) :
    IsUnit m := by
  have hm : m ∈ Submonoid.closure A := hA ▸ Submonoid.mem_top m
  induction hm using Submonoid.closure_induction with
  | mem a ha => exact h a ha
  | one => exact isUnit_one
  | mul a b _ _ iha ihb => exact iha.mul ihb

/-- Proper submonoids of a finite monoid are strictly smaller
[blueprint `lem:submonoid-card`] — the right factor's measure drop in
the milestone-8 induction. Bare counting via `Finite.card_subtype_lt`
(unlike the subgroup version in `GroupCase.lean`, which went through
the quotient's cardinality). -/
theorem card_submonoid_lt_of_ne_top (N : Submonoid M) (h : N ≠ ⊤) :
    Nat.card ↥N < Nat.card M := by
  obtain ⟨m, hm⟩ : ∃ m, m ∉ N := by
    by_contra h'
    push Not at h'
    exact h ((Submonoid.eq_top_iff' N).mpr h')
  exact Finite.card_subtype_lt (p := (· ∈ N)) hm

/-- The generator split [blueprint `lem:gen-split`]: a finite monoid
with a non-unit is generated by a proper submonoid `N` together with a
non-unit `c` — exactly the hypothesis tuple of [DKS] Thm 3.1
(`decomposition`). Proof: a minimal-cardinality generating finset has
a non-unit element `c` (else `isUnit_of_generators_units` makes every
element a unit), and `N := ⟨A ∖ {c}⟩` is proper by minimality. All
`Finset`/decidability bookkeeping stays inside the proof — the
statement is decidability-free. -/
theorem exists_gen_nonunit (hM : ¬ ∀ m : M, IsUnit m) :
    ∃ (N : Submonoid M) (c : M), ¬ IsUnit c ∧ N ≠ ⊤ ∧
      Submonoid.closure (↑N ∪ {c}) = ⊤ := by
  classical
  let _ := Fintype.ofFinite M
  -- minimal-cardinality generating finset
  obtain ⟨A, hA, hmin⟩ := Finset.exists_min_image
    (Finset.univ.filter fun B : Finset M => Submonoid.closure (B : Set M) = ⊤)
    Finset.card
    ⟨Finset.univ, Finset.mem_filter.mpr ⟨Finset.mem_univ _, by
      simp [Submonoid.closure_univ]⟩⟩
  have hAgen : Submonoid.closure (A : Set M) = ⊤ := (Finset.mem_filter.mp hA).2
  have hmin' : ∀ B : Finset M, Submonoid.closure (B : Set M) = ⊤ →
      A.card ≤ B.card := fun B hB =>
    hmin B (Finset.mem_filter.mpr ⟨Finset.mem_univ B, hB⟩)
  -- some generator is a non-unit
  have hex : ∃ c ∈ A, ¬ IsUnit c := by
    by_contra hall
    push Not at hall
    exact hM fun m => isUnit_of_generators_units (A : Set M) hAgen
      (fun a ha => hall a ha) m
  obtain ⟨c, hcA, hc⟩ := hex
  refine ⟨Submonoid.closure ((A.erase c : Finset M) : Set M), c, hc, ?_, ?_⟩
  · -- proper: c ∈ closure (A.erase c) would beat A's minimality
    intro htop
    have hcmem : c ∈ Submonoid.closure ((A.erase c : Finset M) : Set M) :=
      htop ▸ Submonoid.mem_top c
    have hgen' : Submonoid.closure ((A.erase c : Finset M) : Set M) = ⊤ := by
      rw [eq_top_iff, ← hAgen]
      refine Submonoid.closure_le.mpr fun a ha => ?_
      by_cases hac : a = c
      · exact hac ▸ hcmem
      · exact Submonoid.subset_closure (Finset.mem_erase.mpr ⟨hac, ha⟩)
    have h1 := hmin' (A.erase c) hgen'
    have h2 : (A.erase c).card < A.card := Finset.card_erase_lt_of_mem hcA
    omega
  · -- ↑N ∪ {c} recovers A, which generates
    rw [eq_top_iff, ← hAgen]
    refine Submonoid.closure_le.mpr fun a ha => ?_
    by_cases hac : a = c
    · exact Submonoid.subset_closure (Or.inr (by simp [hac]))
    · exact Submonoid.subset_closure
        (Or.inl (Submonoid.subset_closure (Finset.mem_erase.mpr ⟨hac, ha⟩)))

end KRTheory
